version: '3.7'

networks:
  sqr:

services:
  fastapi_app:
    container_name: fastapi_app
    restart: always
    build:
      context: ./src/
      dockerfile: ./fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - sqr

  streamlit_app:
    container_name: streamlit_app
    restart: always
    build:
      context: ./src/streamlit_app/
      dockerfile: ./Dockerfile
    ports:
       - "8080:8080"
    networks:
      - sqr
