name: 'Init'
description: Run docker and necessary deps

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
  - uses: actions/setup-python@v4
    with:
      python-version: 3.11.8

  - uses: actions/cache@v2
    id: cache-venv  # name for referring later
    with:
      path: ./venv/
      key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}-${{ hashFiles('**/pyproject.toml') }}
      restore-keys: |
        ${{ runner.os }}-venv-

  - name: Init
    shell: bash
    run: make init
    if: steps.cache-venv.outputs.cache-hit != 'true'