name: CI
on: pull_request

permissions:
  checks: write
  contents: write
  pull-requests: write
  security-events: write

jobs:
  pylint-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        uses: ./.github/actions/init

      - name: Add matcher
        run: echo "::add-matcher::.github/matchers/pylint.json"

      - name: Run pylint
        run: make lint-pylint SILENT=1

  flake8-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        uses: ./.github/actions/init

      - name: Add matcher
        run: echo "::add-matcher::.github/matchers/flake8.json"

      - name: Run flake8
        run: make lint-flake8 SILENT=1
        

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        uses: ./.github/actions/init
      # - name: Run tests
      #   run: |
      #     make ARGS="-k unit --junitxml=$(pwd)/report.junit.xml" coverage-backend | tee pytest-coverage.txt || true
      - name: Run tests
        run:
          make coverage-backend \
            coverage_report_output=coverage_report/unit \
            ARGS="-k unit --junitxml=$(pwd)/unit.junit.xml" | tee unit-coverage.txt || true

          make coverage-backend \
            coverage_report_output=coverage_report/e2e \
            ARGS="-k e2e --junitxml=$(pwd)/e2e.junit.xml" | tee e2e-coverage.txt || true

          make coverage-backend \
            coverage_report_output=coverage_report/service \
            ARGS="-k service --junitxml=$(pwd)/service.junit.xml" | tee service-coverage.txt || true

          make coverage-backend \
            coverage_report_output=coverage_report/uncategorized \
            ARGS="-k 'not unit and not e2e and not service' --junitxml=$(pwd)/misc.junit.xml" | tee misc-coverage.txt || true

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "*.junit.xml"
      
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        if: success() || failure()
        with:
          # pytest-coverage-path: pytest-coverage.txt
          # junitxml-path: report.junit.xml
          # title: Coverage Report
          multiple-files: |
            Unit tests, unit-coverage.txt, unit.junit.xml
            E2E tests, e2e-coverage.txt, e2e.junit.xml
            Service tests, service-coverage.txt, service.junit.xml
            Misc tests, misc-coverage.txt, misc.junit.xml
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: Coverage report
          path: coverage_report

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        uses: ./.github/actions/init

      - name: Backend check
        run: make security-backend ARGS="-f sarif -o $(pwd)/backend.bandit.sarif --exit-zero"
      - name: Frontend check
        run: make security-frontend ARGS="-f sarif -o $(pwd)/frontend.bandit.sarif --exit-zero"

      - name: Upload fbackend SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: backend.bandit.sarif
          category: bandit-backend
      - name: Upload frontend SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: frontend.bandit.sarif
          category: bandit-frontend

      - name: Upload SARIF reports as artifacts
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: security_reports
          path: '*.sarif'

  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init
        uses: ./.github/actions/init

      - name: Start docker-compose
        run: make docker-run ARGS='-d --wait --wait-timeout 60'
      - name: Stop docker-compose
        if: success() || failure()
        run: docker-compose down